import type { Metadata } from "next";
import "@/../styles/globals.css";
import Sidebar from "@/components/modules/sidebar/Sidebar";
import Navbar from "@/components/modules/navbar/Navbar";

export const metadata: Metadata = {
  title: "Education CMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body
        className={`antialiased`}
      >
            <div className="container">
              <Sidebar />
        
              <main className="main">
                <Navbar />
                {children}
              </main>
            </div>
      </body>
    </html>
  );
}
